const mongoose = require('mongoose');

const submissionSchema = new mongoose.Schema({
  assignmentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Assignment',
    required: true
  },
  studentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  fileUrl: {
    type: String, // AWS S3 URL
    required: true
  },
  fileName: {
    type: String
  },
  textExtracted: {
    type: String // OCR output from Tesseract.js
  },
  duplicateScore: {
    type: Number,
    default: 0 // Generated by semantic comparison in Pinecone
  },
  isFlagged: {
    type: Boolean,
    default: false
  },
  marks: {
    type: Number
  },
  feedback: {
    type: String
  },
  status: {
    type: String,
    enum: ['submitted', 'flagged', 'graded'],
    default: 'submitted'
  },
  submittedAt: {
    type: Date,
    default: Date.now
  }
});

module.exports = mongoose.model('Submission', submissionSchema);
